[package]
name = "peach"
version = "0.2.5"
authors = ["rxxuzi"]
edition = "2024"
description = "Peach programming language"
repository = "https://github.com/rxxuzi/peach"
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"

[[bin]]
name = "peach"
path = "src/main.rs"

[[bin]]
name = "pc"
path = "src/bin/pc.rs"